const alb99Names = {
    "Ar-Rahmaan": "I Gjithëmëshirshmi",
    "Ar-Raheem": "Mëshirëploti",
    "Al-Malik": "Sunduesi",
    "Al-Quddus": "I Shenjti, I Pastri nga çdo e metë",
    "As-Salaam": "Paqedhënësi",
    "Al-Mu'min": "Siguruesi",
    "Al-Muhaymin": "Mbizotëruesi, Mbikëqyrësi",
    "Al-Azeez": "I Plotfuqishmi",
    "Al-Jabbaar": "I Gjithëfuqishmi, Detyruesi",
    "Al-Mutakabbir": "Krenari, I Madhërishmi",
    "Al-Khaaliq": "Krijuesi nga mosekzistenca",
    "Al-Baari'": "Fillesëdhënësi",
    "Al-Musawwir": "Piktori, Formëdhënësi",
    "Al-Ghaffaar": "Gjithëfalësi",
    "Al-Qahhaar": "Mposhtësi",
    "Al-Wahhaab": "Dhuruesi",
    "Ar-Razzaaq": "Furnizuesi",
    "Al-Fattaah": "Hapësi, Zgjidhësi",
    "Al-Aleem": "I Gjithëdituri",
    "Al-Qaabidh": "Shtrënguesi, Kufizuesi",
    "Al-Baasit": "Zgjeruesi, Dhënësi",
    "Al-Khaafidh": "Përulësi",
    "Ar-Raafi'": "Lartësuesi",
    "Al-Mu'izz": "Ngritësi, Nderdhënësi",
    "Al-Muzil": "Poshtëruesi",
    "As-Sami'": "Gjithëdëgjuesi",
    "Al-Baseer": "Gjithëshikuesi",
    "Al-Hakam": "Gjykatësi",
    "Al-Adl": "I Drejti",
    "Al-Lateef": "I Buti, Bamirësi",
    "Al-Khabeer": "I Gjithënjoftuari",
    "Al-Haleem": "I Përmbajturi",
    "Al-Atheem": "I Madhërishmi",
    "Al-Ghafoor": "Gjithëfalësi",
    "Ash-Shakoor": "Mirënjohësi, Falënderuesi",
    "Al-Aliyy": "I Larti",
    "Al-Kabeer": "I Madhi",
    "Al-Hafeedh": "Ruajtësi",
    "Al-Muqeet": "Ushqyesi",
    "Al-Haseeb": "Llogaritësi",
    "Al-Jaleel": "I Fisniku",
    "Al-Kareem": "Bujari",
    "Ar-Raqeeb": "Mbikëqyrësi",
    "Al-Mujeeb": "Lutjepranuesi",
    "Al-Waasi'": "Gjithëpërfshirësi",
    "Al-Hakeem": "I Urti",
    "Al-Wadood": "Më Atesionuari, I Dashuri",
    "Al-Majeed": "I Lavdishmi",
    "Al-Baa'ith": "Ringjallësi",
    "Ash-Shaheed": "Dëshmuesi",
    "Al-Haqq": "E Vërteta",
    "Al-Wakeel": "Kujdestari, Zëvendësi",
    "Al-Qawiyy": "I Forti",
    "Al-Mateen": "I Pathyeshmi",
    "Al-Waliyy": "Mbrojtësi",
    "Al-Hameed": "I Falënderuari",
    "Al-Muhsee": "Numëruesi, Përfshirësi",
    "Al-Mubdi": "Nismëtari, Krijuesi i parë",
    "Al-Mu'eed": "Rikrijuesi",
    "Al-Muhyi": "Jetëdhënësi",
    "Al-Mumeet": "Jetëmarrësi",
    "Al-Hayy": "I Gjalli",
    "Al-Qayyoom": "I Përjetshmi, Përmbajtësi",
    "Al-Waajid": "Zbuluesi",
    "Al-Maajid": "I Lavdishmi",
    "Al-Waahid": "I Vetmi",
    "Al-Ahad": "Njëshi",
    "As-Samad": "Strehimtari, I Panevojshëm",
    "Al-Qaadir": "I Fuqishmi",
    "Al-Muqtadir": "I Plotfuqishmi",
    "Al-Muqaddim": "Nismëtari",
    "Al-Mu'akhkhir": "Prapëmbajtësi",
    "Al-Awwal": "I Pari",
    "Al-Aakhir": "I Fundit",
    "Adh-Dhaahir": "I Dukshmi",
    "Al-Baatin": "I Padukshmi, I Brendshmi",
    "Al-Waali": "Sundimtari",
    "Al-Muta'aali": "Shumë i Larti",
    "Al-Barr": "Miku i Mirë, Bamirësi",
    "At-Tawwaab": "Pranuesi i Pendimeve",
    "Al-Muntaqim": "Ndëshkuesi",
    "Al-Afuww": "Falësi",
    "Ar-Ra'oof": "Mëshiruesi i Butë",
    "Maalik-ul-Mulk": "Pronari i Pushtetit",
    "Dhul-Jalaali-wal-Ikraam": "Zoti i Madhështisë dhe i Nderit",
    "Al-Muqsit": "I Drejti, Paqëtuesi",
    "Al-Jaami'": "Tubuesi",
    "Al-Ghaniyy": "I Pasuri",
    "Al-Mughni": "Pasuridhënësi",
    "Al-Maani'": "Mbrojtësi, Parandaluesi",
    "Ad-Daarr": "Lënduesi (për një urtësi)",
    "An-Naafi'": "Dobi-sjellësi",
    "An-Noor": "Drita",
    "Al-Haadi": "Udhëzuesi",
    "Al-Badee'": "Shpikësi",
    "Al-Baaqi": "I Përhershmi",
    "Al-Waarith": "Trashëgimtari",
    "Ar-Rasheed": "Udhëzuesi i Drejtë",
    "As-Saboor": "I Durueshmi"
};
